For this first assignment we will study the golden ball player of the 2023 Women's World Cup, Aitana Bonmatí.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsbombpy import sb
from mplsoccer import Pitch

First of all let's find the competition we need.

In [2]:
competitions_df = sb.competitions()
competitions_df

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2023-08-17T23:51:11.837478,None,None,2023-08-17T23:51:11.837478
1,16,4,Europe,Champions League,male,False,False,2018/2019,2023-03-07T12:20:48.118250,2021-06-13T16:17:31.694,None,2023-03-07T12:20:48.118250
2,16,1,Europe,Champions League,male,False,False,2017/2018,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-01-23T21:55:30.425330
3,16,2,Europe,Champions League,male,False,False,2016/2017,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
4,16,27,Europe,Champions League,male,False,False,2015/2016,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
...,...,...,...,...,...,...,...,...,...,...,...,...
62,55,43,Europe,UEFA Euro,male,False,True,2020,2023-02-24T21:26:47.128979,2023-04-27T22:38:34.970148,2023-04-27T22:38:34.970148,2023-02-24T21:26:47.128979
63,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2023-06-18T19:28:39.443883,2021-06-13T16:17:31.694,None,2023-06-18T19:28:39.443883
64,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2023-07-17T21:19:03.032991,2023-07-17T21:21:56.497106,2023-07-17T21:21:56.497106,2023-07-17T21:19:03.032991
65,72,107,International,Women's World Cup,female,False,True,2023,2023-09-01T12:34:19.705316,2023-09-01T12:35:45.762196,2023-09-01T12:35:45.762196,2023-09-01T12:34:19.705316
66,72,30,International,Women's World Cup,female,False,True,2019,2023-07-27T10:33:48.273734,2021-06-13T16:17:31.694,None,2023-07-27T10:33:48.273734

In [3]:
competitions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   competition_id             67 non-null     int64
 1   season_id                  67 non-null     int64
 2   country_name               67 non-null     object
 3   competition_name           67 non-null     object
 4   competition_gender         67 non-null     object
 5   competition_youth          67 non-null     bool
 6   competition_international  67 non-null     bool
 7   season_name                67 non-null     object
 8   match_updated              67 non-null     object
 9   match_updated_360          51 non-null     object
 10  match_available_360        5 non-null      object
 11  match_available            67 non-null     object
dtypes: bool(2), int64(2), object(8)
memory usage: 5.5+ KB

In [4]:
competitions_df.competition_name.unique()

array(['1. Bundesliga', 'Champions League', 'Copa del Rey',
       "FA Women's Super League", 'FIFA U20 World Cup', 'FIFA World Cup',
       'Indian Super league', 'La Liga', 'Liga Profesional', 'Ligue 1',
       'North American League', 'NWSL', 'Premier League', 'Serie A',
       'UEFA Euro', 'UEFA Europa League', "UEFA Women's Euro",
       "Women's World Cup"], dtype=object)

In [5]:
competition_name = "Women's World Cup"
competitions_df[competitions_df['competition_name'] == competition_name]

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
65,72,107,International,Women's World Cup,female,False,True,2023,2023-09-01T12:34:19.705316,2023-09-01T12:35:45.762196,2023-09-01T12:35:45.762196,2023-09-01T12:34:19.705316
66,72,30,International,Women's World Cup,female,False,True,2019,2023-07-27T10:33:48.273734,2021-06-13T16:17:31.694,None,2023-07-27T10:33:48.273734

In [6]:
competition_id = 72
season_id = 107

wwc2023 = competitions_df[(competitions_df['competition_id'] == competition_id) & (competitions_df['season_id'] == season_id)]
wwc2023

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
65,72,107,International,Women's World Cup,female,False,True,2023,2023-09-01T12:34:19.705316,2023-09-01T12:35:45.762196,2023-09-01T12:35:45.762196,2023-09-01T12:34:19.705316

In [7]:
help(sb.competition_events)

Help on function competition_events in module statsbombpy.sb:

competition_events(country: str, division: str, season: str, gender: str = 'male', split: bool = False, filters: dict = {}, fmt: str = 'dataframe', creds: dict = {'user': None, 'passwd': None}, include_360_metrics=False) -> Union[pandas.core.frame.DataFrame, dict]

In [8]:
matches_df = sb.matches(competition_id, season_id)
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   match_id               64 non-null     int64
 1   match_date             64 non-null     object
 2   kick_off               64 non-null     object
 3   competition            64 non-null     object
 4   season                 64 non-null     object
 5   home_team              64 non-null     object
 6   away_team              64 non-null     object
 7   home_score             64 non-null     int64
 8   away_score             64 non-null     int64
 9   match_status           64 non-null     object
 10  match_status_360       64 non-null     object
 11  last_updated           64 non-null     object
 12  last_updated_360       64 non-null     object
 13  match_week             64 non-null     int64
 14  competition_stage      64 non-null     object
 15  stadium                64 non-null     object
 16  referee                63 non-null     object
 17  home_managers          64 non-null     object
 18  away_managers          64 non-null     object
 19  data_version           64 non-null     object
 20  shot_fidelity_version  64 non-null     object
 21  xy_fidelity_version    64 non-null     object
dtypes: int64(4), object(18)
memory usage: 11.1+ KB

In [9]:
unique_home_teams = set(matches_df['home_team'])
unique_away_teams = set(matches_df['away_team'])

unique_teams = unique_home_teams.union(unique_away_teams)
unique_teams

{"Argentina Women's",
 "Australia Women's",
 "Brazil Women's",
 "Canada Women's",
 "China PR Women's",
 "Colombia Women's",
 "Costa Rica Women's",
 "Denmark Women's",
 "England Women's",
 "France Women's",
 "Germany Women's",
 "Haiti Women's",
 "Italy Women's",
 "Jamaica Women's",
 "Japan Women's",
 "Korea Republic Women's",
 "Morocco Women's",
 "Netherlands Women's",
 "New Zealand Women's",
 "Nigeria Women's",
 "Norway Women's",
 "Panama Women's",
 "Philippines Women's",
 "Portugal Women's",
 "Republic of Ireland Women's",
 "South Africa Women's",
 "Spain Women's",
 "Sweden Women's",
 "Switzerland Women's",
 "United States Women's",
 "Vietnam Women's",
 "Zambia Women's"}

In [10]:
top2_teams = ["Spain Women's", "England Women's"]
top4_teams = top2_teams + ["Sweden Women's", "Australia Women's"]
top8_teams = top4_teams + ["Netherlands Women's", "Japan Women's", "Colombia Women's", "France Women's"]

In [11]:
team_name = "Spain Women's"
# team_mask = (matches_df['home_team'] == team_name) | (matches_df['away_team'] == team_name)
# team_matches_df = matches_df[team_mask]
# team_matches_df

In [12]:
# team_matches_id = list(team_matches_df.match_id)
# team_matches_id

In [13]:
# dataframes_to_concatenate = []
# for match_id in team_matches_id:
#     events = sb.events(match_id)
#     dataframes_to_concatenate.append(events)
    
# wwc2023_spain_matches_events = pd.concat(dataframes_to_concatenate, ignore_index=True)

In [14]:
# team_events_mask = wwc2023_spain_matches_events['team'] == team_name
# wwc2023_spain_events = wwc2023_spain_matches_events[team_events_mask]

In [15]:
# passes2_df = wwc2023_spain_events[wwc2023_spain_events.type == 'Pass']
# passes2_df

In [16]:
# passes2_df.groupby('match_id').size().reset_index(name='count')

In [17]:
wwc2023_events = sb.competition_events(
    country=wwc2023['country_name'].iloc[0],
    division=wwc2023['competition_name'].iloc[0],
    season=wwc2023['season_name'].iloc[0],
    gender=wwc2023['competition_gender'].iloc[0],
    split=True
)

In [18]:
passes_and_carrys = pd.concat([wwc2023_events["carrys"], wwc2023_events["passes"]], axis=0).reset_index(drop=True)
aitana_match = passes_and_carrys[(passes_and_carrys.player == "Aitana Bonmati Conca") & (passes_and_carrys.match_id == 3893791)]
aitana_match.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type',
       'possession', 'possession_team', 'play_pattern', 'team', 'player',
       'position', 'location', 'duration', 'related_events', 'match_id',
       'carry_end_location', 'possession_team_id', 'team_id', 'player_id',
       'under_pressure', 'pass_recipient', 'pass_length', 'pass_angle',
       'pass_height', 'pass_end_location', 'pass_body_part', 'pass_type',
       'pass_outcome', 'pass_switch', 'pass_aerial_won', 'off_camera',
       'pass_cross', 'pass_through_ball', 'pass_technique',
       'pass_assisted_shot_id', 'pass_shot_assist', 'pass_outswinging',
       'pass_straight', 'pass_inswinging', 'counterpress', 'pass_goal_assist',
       'pass_cut_back', 'pass_no_touch', 'pass_deflected',
       'pass_miscommunication', 'out'],
      dtype='object')

In [19]:
carrys = wwc2023_events["carrys"]
passes = wwc2023_events["passes"]

In [20]:
match_id = 3893791

aitana_match_carrys_mask = (carrys.player == "Aitana Bonmati Conca") & (carrys.match_id == match_id)
aitana_match_carrys = carrys[aitana_match_carrys_mask]

In [21]:
aitana_match_passes_mask = (passes.player == "Aitana Bonmati Conca") & (passes.match_id == match_id)
aitana_match_passes = passes[aitana_match_passes_mask]

In [22]:
aitana_match_passes.id

35051    4a34b16e-e971-4355-ab0b-f7a741bfa759
35082    a152f5ab-d82d-4d14-9489-fe81bf7999f1
35098    05325193-0619-4fbd-b942-421e472521e2
35109    31ba94cd-8d34-4e9c-bf13-6ea639822116
35114    8c14018e-4b2d-4eed-991b-8b72a9196760
                         ...
35865    6b9f8f02-18c9-447b-ab40-518c2aacf303
35868    f12156e4-54c6-4a2b-9d03-c9333b90165e
35872    42cbb068-a802-4a22-a68d-6895a0b561f4
35880    8d9f3da1-cb99-454a-812d-9c90dc70020f
35891    4163f610-99b5-4386-86c7-e7aabfcb11f3
Name: id, Length: 66, dtype: object

In [42]:
# Create a function to get the related pass event IDs
def get_related_pass_ids(related_events):
    pass_ids = []
    for event_id in related_events:
        if event_id in aitana_match_passes.id:
            pass_ids.append(event_id)
    return pass_ids

# Apply the function to each row in the carry DataFrame
aitana_match_carrys['related_pass_event'] = aitana_match_carrys['related_events'].apply(get_related_pass_ids)
aitana_match_carrys

C:\Users\alvar\AppData\Local\Temp\ipykernel_14632\3815695832.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aitana_match_carrys['related_pass_event'] = aitana_match_carrys['related_events'].apply(get_related_pass_ids)

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,location,duration,related_events,match_id,carry_end_location,possession_team_id,team_id,player_id,under_pressure,related_pass_event
27518,31dc1875-f24b-4ef4-af1e-916aa0b56ad9,10,1,00:00:03.847,0,3,Carry,2,Spain Women's,From Kick Off,...,"[47.7, 51.7]",1.518906,"[4a34b16e-e971-4355-ab0b-f7a741bfa759, 943aca2...",3893791,"[52.6, 55.7]",863,863,15284,NaN,[]
27544,ef096ab4-d229-4ca5-8416-65b4eaee66e1,104,1,00:02:25.511,2,25,Carry,5,Spain Women's,From Throw In,...,"[97.9, 67.3]",0.248971,"[2d7f6d3c-0d64-4bf6-9b4f-b26db7fb1c9b, 7d700fd...",3893791,"[97.8, 65.6]",863,863,15284,True,[]
27557,36f9caad-1906-4fd9-9754-c068154ec139,158,1,00:03:24.421,3,24,Carry,5,Spain Women's,From Throw In,...,"[81.4, 72.3]",4.775616,"[05325193-0619-4fbd-b942-421e472521e2, f8dedd3...",3893791,"[79.3, 69.7]",863,863,15284,True,[]
27566,8fef9adf-0424-420a-85c7-32dc11e9e368,198,1,00:04:26.963,4,26,Carry,7,Spain Women's,Regular Play,...,"[87.8, 38.7]",1.219263,"[31ba94cd-8d34-4e9c-bf13-6ea639822116, d87038f...",3893791,"[85.3, 41.7]",863,863,15284,True,[]
27571,707d21b4-4f87-426d-b3be-2442fa77305f,216,1,00:04:43.903,4,43,Carry,7,Spain Women's,Regular Play,...,"[110.2, 78.0]",2.795192,"[50c473e1-affd-4cb2-aaa8-977e5b3cf43d, 8c14018...",3893791,"[111.5, 74.9]",863,863,15284,True,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28176,5e52050c-355b-42c1-9c36-12301ace4e88,3188,2,00:46:34.667,91,34,Carry,157,Spain Women's,From Throw In,...,"[108.7, 59.2]",0.485323,"[23f9679f-16f0-4804-afac-0715a7fac9a3, 37d8abc...",3893791,"[108.7, 57.4]",863,863,15284,NaN,[]
28177,90eef518-a91e-41dc-bc14-c00954ddf98e,3192,2,00:46:37.732,91,37,Carry,157,Spain Women's,From Throw In,...,"[116.4, 66.9]",1.129409,"[08228740-3206-4964-a5d2-8043ea85d4c8, f12156e...",3893791,"[114.5, 70.1]",863,863,15284,NaN,[]
28182,6306ee9f-d220-4a53-bd24-066e434406c4,3212,2,00:46:49.158,91,49,Carry,157,Spain Women's,From Throw In,...,"[103.8, 65.7]",2.172572,"[42cbb068-a802-4a22-a68d-6895a0b561f4, 6e8cc8c...",3893791,"[108.6, 72.0]",863,863,15284,True,[]
28189,f337079c-b086-4215-9798-a9ba3a72d933,3253,2,00:47:52.381,92,52,Carry,159,Spain Women's,Other,...,"[91.3, 49.4]",0.366499,"[194acba4-14b7-4f5f-8266-21e1cb3909ea, 8d9f3da...",3893791,"[91.3, 50.2]",863,863,15284,NaN,[]
28196,c5cfe043-724d-43f9-a686-9b969d2c41c3,3287,2,00:48:42.026,93,42,Carry,161,Spain Women's,Regular Play,...,"[64.1, 29.1]",1.371700,"[4163f610-99b5-4386-86c7-e7aabfcb11f3, 629c1a3...",3893791,"[63.7, 31.9]",863,863,15284,NaN,[]

In [24]:
uuid = '5d3b3608-7cf4-4c4b-895a-abf2ccae2aa0'
aitana_match_passes[aitana_match_passes['id'] == uuid]

Empty DataFrame
Columns: [id, index, period, timestamp, minute, second, type, possession, possession_team, play_pattern, team, player, position, location, duration, related_events, match_id, pass_recipient, pass_length, pass_angle, pass_height, pass_end_location, pass_body_part, pass_type, possession_team_id, team_id, player_id, pass_outcome, under_pressure, pass_switch, pass_aerial_won, off_camera, pass_cross, pass_through_ball, pass_technique, pass_assisted_shot_id, pass_shot_assist, pass_outswinging, pass_straight, pass_inswinging, counterpress, pass_goal_assist, pass_cut_back, pass_no_touch, pass_deflected, pass_miscommunication, out]
Index: []

[0 rows x 47 columns]

In [25]:
aitana_match_carrys[['id', 'location', 'carry_end_location', 'related_pass_event']]

,id,location,carry_end_location,related_pass_event
27518,31dc1875-f24b-4ef4-af1e-916aa0b56ad9,"[47.7, 51.7]","[52.6, 55.7]",[]
27544,ef096ab4-d229-4ca5-8416-65b4eaee66e1,"[97.9, 67.3]","[97.8, 65.6]",[]
27557,36f9caad-1906-4fd9-9754-c068154ec139,"[81.4, 72.3]","[79.3, 69.7]",[]
27566,8fef9adf-0424-420a-85c7-32dc11e9e368,"[87.8, 38.7]","[85.3, 41.7]",[]
27571,707d21b4-4f87-426d-b3be-2442fa77305f,"[110.2, 78.0]","[111.5, 74.9]",[]
...,...,...,...,...
28176,5e52050c-355b-42c1-9c36-12301ace4e88,"[108.7, 59.2]","[108.7, 57.4]",[]
28177,90eef518-a91e-41dc-bc14-c00954ddf98e,"[116.4, 66.9]","[114.5, 70.1]",[]
28182,6306ee9f-d220-4a53-bd24-066e434406c4,"[103.8, 65.7]","[108.6, 72.0]",[]
28189,f337079c-b086-4215-9798-a9ba3a72d933,"[91.3, 49.4]","[91.3, 50.2]",[]
28196,c5cfe043-724d-43f9-a686-9b969d2c41c3,"[64.1, 29.1]","[63.7, 31.9]",[]

In [26]:
aitana_match_carrys[['id', 'related_events', 'related_pass_event']]

,id,related_events,related_pass_event
27518,31dc1875-f24b-4ef4-af1e-916aa0b56ad9,"[4a34b16e-e971-4355-ab0b-f7a741bfa759, 943aca2...",[]
27544,ef096ab4-d229-4ca5-8416-65b4eaee66e1,"[2d7f6d3c-0d64-4bf6-9b4f-b26db7fb1c9b, 7d700fd...",[]
27557,36f9caad-1906-4fd9-9754-c068154ec139,"[05325193-0619-4fbd-b942-421e472521e2, f8dedd3...",[]
27566,8fef9adf-0424-420a-85c7-32dc11e9e368,"[31ba94cd-8d34-4e9c-bf13-6ea639822116, d87038f...",[]
27571,707d21b4-4f87-426d-b3be-2442fa77305f,"[50c473e1-affd-4cb2-aaa8-977e5b3cf43d, 8c14018...",[]
...,...,...,...
28176,5e52050c-355b-42c1-9c36-12301ace4e88,"[23f9679f-16f0-4804-afac-0715a7fac9a3, 37d8abc...",[]
28177,90eef518-a91e-41dc-bc14-c00954ddf98e,"[08228740-3206-4964-a5d2-8043ea85d4c8, f12156e...",[]
28182,6306ee9f-d220-4a53-bd24-066e434406c4,"[42cbb068-a802-4a22-a68d-6895a0b561f4, 6e8cc8c...",[]
28189,f337079c-b086-4215-9798-a9ba3a72d933,"[194acba4-14b7-4f5f-8266-21e1cb3909ea, 8d9f3da...",[]
28196,c5cfe043-724d-43f9-a686-9b969d2c41c3,"[4163f610-99b5-4386-86c7-e7aabfcb11f3, 629c1a3...",[]

In [27]:
aitana_match['related_events']

27518    [4a34b16e-e971-4355-ab0b-f7a741bfa759, 943aca2...
27544    [2d7f6d3c-0d64-4bf6-9b4f-b26db7fb1c9b, 7d700fd...
27557    [05325193-0619-4fbd-b942-421e472521e2, f8dedd3...
27566    [31ba94cd-8d34-4e9c-bf13-6ea639822116, d87038f...
27571    [50c473e1-affd-4cb2-aaa8-977e5b3cf43d, 8c14018...
                               ...
82654               [0550a886-6580-467b-89ef-a5d2edc7996f]
82657               [6ff48c8d-6d87-4e09-9ee4-6244ec9955a8]
82661    [9a34f385-ac99-4048-a869-cbf3b5ef9dc0, ea4a5fc...
82669               [ff5fb119-5cb6-4847-b158-d4c6902829d3]
82680               [6b45b109-804a-49c8-8060-8d5e737fff33]
Name: related_events, Length: 136, dtype: object

In [28]:
wwc2023_events["carrys"]

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,position,location,duration,related_events,match_id,carry_end_location,possession_team_id,team_id,player_id,under_pressure
0,7c8df29f-286a-40cc-b161-baaa428e182e,7,1,00:00:00.932,0,0,Carry,2,England Women's,From Kick Off,...,Left Defensive Midfield,"[51.5, 38.5]",0.469323,"[1f05edf6-cb89-467b-bce3-c40acf39cb47, 82cda67...",3904629,"[50.6, 38.5]",865,865,4658,NaN
1,bd45fc41-4fbb-4099-b321-519a7705bf6b,10,1,00:00:03.409,0,3,Carry,2,England Women's,From Kick Off,...,Center Back,"[31.1, 46.3]",1.597814,"[7cb846aa-124a-401b-8148-98d911970fcd, b9e2076...",3904629,"[34.8, 54.0]",865,865,4642,NaN
2,3bdaf03c-d20d-46a3-9b4c-e70c3b49b46b,16,1,00:00:08.978,0,8,Carry,2,England Women's,From Kick Off,...,Right Defensive Midfield,"[80.9, 60.1]",3.136559,"[4c8f4cf7-d2f0-4953-b27b-1080fefa2398, 9d67b40...",3904629,"[69.0, 54.1]",865,865,4643,True
3,b70a3833-de08-4d2c-928c-d28f2358c793,20,1,00:00:14.098,0,14,Carry,2,England Women's,From Kick Off,...,Center Back,"[39.7, 47.1]",0.875012,"[3e797488-c543-401f-99c0-3e5e8e439adb, 54991f6...",3904629,"[37.5, 45.6]",865,865,4642,NaN
4,b6e9f4b5-0260-4d27-b266-791b1200f175,23,1,00:00:16.992,0,16,Carry,2,England Women's,From Kick Off,...,Goalkeeper,"[12.3, 37.3]",2.657896,"[0f25a2f5-5ec5-45c8-bcee-e7357179f2cf, b0388bf...",3904629,"[15.9, 35.9]",865,865,31538,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46784,c5c8bac9-a5b3-4eee-9318-b73c5ce34f8c,3949,2,00:51:13.411,96,13,Carry,203,Zambia Women's,From Goal Kick,...,Right Center Midfield,"[60.0, 3.1]",1.977744,"[07223799-dd12-4a22-96a9-0682b28b388c, 6285c4c...",3893793,"[51.6, 2.3]",6045,6045,131617,True
46785,d83a3da5-8da6-40ae-a7eb-8ea91d44e6ea,3957,2,00:51:25.310,96,25,Carry,205,Japan Women's,Regular Play,...,Right Defensive Midfield,"[57.7, 75.8]",0.458271,"[09bfeb68-36c3-4848-ae15-ba85c5b77abc, f249814...",3893793,"[57.7, 75.8]",1210,1210,25632,NaN
46786,4d1d3d2f-56fe-45ee-bc67-9147fbff44f6,3962,2,00:51:27.377,96,27,Carry,205,Japan Women's,Regular Play,...,Center Forward,"[72.1, 72.3]",0.148451,"[2483c640-347f-4ccb-9415-6ad71ad62653, f7b7f25...",3893793,"[72.1, 72.3]",1210,1210,401933,NaN
46787,6114cee0-cc37-4de7-8e63-e319a38d9ce7,3965,2,00:51:28.418,96,28,Carry,205,Japan Women's,Regular Play,...,Right Defensive Midfield,"[63.3, 61.2]",1.359290,"[02eace19-8fef-4b15-a664-4c831cf39824, 80645ec...",3893793,"[69.0, 57.1]",1210,1210,25632,NaN
46788,7140d822-6470-4589-ad95-8011f607c8f2,3969,2,00:51:32.609,96,32,Carry,205,Japan Women's,Regular Play,...,Left Wing,"[102.8, 52.0]",0.310845,"[1baa5c3f-7cc5-4ec4-92c5-74b4179582b7, 63f5a84...",3893793,"[104.3, 52.5]",1210,1210,401930,True

In [29]:
wwc2023_events["passes"]

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,pass_outswinging,pass_straight,pass_inswinging,counterpress,pass_goal_assist,pass_cut_back,pass_no_touch,pass_deflected,pass_miscommunication,out
0,53b22deb-dd5b-4da4-b947-39849842adcb,5,1,00:00:00.080,0,0,Pass,2,England Women's,From Kick Off,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1f05edf6-cb89-467b-bce3-c40acf39cb47,8,1,00:00:01.402,0,1,Pass,2,England Women's,From Kick Off,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7cb846aa-124a-401b-8148-98d911970fcd,11,1,00:00:05.007,0,5,Pass,2,England Women's,From Kick Off,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a061feb1-95d4-4013-af5b-ebf35e4f72a2,13,1,00:00:07.878,0,7,Pass,2,England Women's,From Kick Off,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4c8f4cf7-d2f0-4953-b27b-1080fefa2398,18,1,00:00:12.115,0,12,Pass,2,England Women's,From Kick Off,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59832,9582979a-7ba1-44f6-9bf5-a8291815e57a,3955,2,00:51:24.656,96,24,Pass,205,Japan Women's,Regular Play,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59833,f249814e-1547-44c0-8db4-9932eca0e714,3958,2,00:51:25.769,96,25,Pass,205,Japan Women's,Regular Play,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59834,5247be79-6ae6-40b0-a5cf-93cc51164fe6,3960,2,00:51:26.384,96,26,Pass,205,Japan Women's,Regular Play,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59835,2483c640-347f-4ccb-9415-6ad71ad62653,3963,2,00:51:27.525,96,27,Pass,205,Japan Women's,Regular Play,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59836,02eace19-8fef-4b15-a664-4c831cf39824,3966,2,00:51:29.777,96,29,Pass,205,Japan Women's,Regular Play,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
wwc2023_events = sb.competition_events(
    country=wwc2023['country_name'].iloc[0],
    division=wwc2023['competition_name'].iloc[0],
    season=wwc2023['season_name'].iloc[0],
    gender=wwc2023['competition_gender'].iloc[0]
)
wwc2023_team_events = wwc2023_events[wwc2023_events['team'] == team_name]
wwc2023_team_events

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_deflection,block_offensive,block_save_block,carry_end_location,clearance_aerial_won,...,shot_technique,shot_type,substitution_outcome,substitution_replacement,tactics,team,team_id,timestamp,type,under_pressure
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Spain Women's,863,00:00:00.000,Starting XI,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",Spain Women's,863,00:00:00.000,Starting XI,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",Spain Women's,863,00:00:00.000,Starting XI,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",Spain Women's,863,00:00:00.000,Starting XI,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",Spain Women's,863,00:00:00.000,Starting XI,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:06:28.275,Referee Ball-Drop,NaN
225998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:47:51.518,Referee Ball-Drop,NaN
226120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:06:49.634,Offside,NaN
226133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:20:13.124,Own Goal For,NaN
226139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:10:54.772,Own Goal Against,NaN

In [31]:
wwc2023_team_events.type.unique()

array(['Starting XI', 'Half Start', 'Pass', 'Ball Receipt*', 'Carry',
       'Ball Recovery', 'Pressure', 'Miscontrol', 'Foul Committed',
       'Foul Won', 'Duel', 'Clearance', 'Dispossessed', '50/50', 'Block',
       'Dribbled Past', 'Dribble', 'Shot', 'Goal Keeper', 'Interception',
       'Half End', 'Tactical Shift', 'Shield', 'Substitution',
       'Injury Stoppage', 'Player Off', 'Player On', 'Referee Ball-Drop',
       'Offside', 'Own Goal For', 'Own Goal Against'], dtype=object)

In [32]:
passes_df = wwc2023_team_events[wwc2023_team_events.type == 'Pass']
passes_df

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_deflection,block_offensive,block_save_block,carry_end_location,clearance_aerial_won,...,shot_technique,shot_type,substitution_outcome,substitution_replacement,tactics,team,team_id,timestamp,type,under_pressure
1310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:00:11.552,Pass,NaN
1311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:00:12.281,Pass,NaN
1313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:00:33.179,Pass,NaN
1314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:00:35.109,Pass,True
1328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:02:07.812,Pass,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:48:43.398,Pass,NaN
36298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:48:48.966,Pass,True
36300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:49:39.733,Pass,True
36301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:49:47.881,Pass,NaN
36302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Spain Women's,863,00:49:49.887,Pass,NaN

In [33]:
passes_df.groupby('match_id').size().reset_index(name='count')

   match_id  count
0   3893791    671
1   3893806    784
2   3893822    939
3   3901733    727
4   3902240    757
5   3904628    558
6   3906390    519

In [34]:
for column in passes_df.columns:
    print(column)

50_50
bad_behaviour_card
ball_receipt_outcome
ball_recovery_offensive
ball_recovery_recovery_failure
block_deflection
block_offensive
block_save_block
carry_end_location
clearance_aerial_won
clearance_body_part
clearance_head
clearance_left_foot
clearance_other
clearance_right_foot
counterpress
dribble_no_touch
dribble_nutmeg
dribble_outcome
dribble_overrun
duel_outcome
duel_type
duration
foul_committed_advantage
foul_committed_card
foul_committed_offensive
foul_committed_penalty
foul_committed_type
foul_won_advantage
foul_won_defensive
foul_won_penalty
goalkeeper_body_part
goalkeeper_end_location
goalkeeper_lost_in_play
goalkeeper_outcome
goalkeeper_penalty_saved_to_post
goalkeeper_position
goalkeeper_punched_out
goalkeeper_shot_saved_off_target
goalkeeper_shot_saved_to_post
goalkeeper_success_in_play
goalkeeper_success_out
goalkeeper_technique
goalkeeper_type
id
index
injury_stoppage_in_chain
interception_outcome
location
match_id
minute
miscontrol_aerial_won
off_camera
out
pass_aerial_won
pass_angle
pass_assisted_shot_id
pass_body_part
pass_cross
pass_cut_back
pass_deflected
pass_end_location
pass_goal_assist
pass_height
pass_inswinging
pass_length
pass_miscommunication
pass_no_touch
pass_outcome
pass_outswinging
pass_recipient
pass_shot_assist
pass_straight
pass_switch
pass_technique
pass_through_ball
pass_type
period
play_pattern
player
player_id
player_off_permanent
position
possession
possession_team
possession_team_id
related_events
second
shot_aerial_won
shot_body_part
shot_deflected
shot_end_location
shot_first_time
shot_follows_dribble
shot_freeze_frame
shot_key_pass_id
shot_one_on_one
shot_open_goal
shot_outcome
shot_redirect
shot_saved_off_target
shot_saved_to_post
shot_statsbomb_xg
shot_technique
shot_type
substitution_outcome
substitution_replacement
tactics
team
team_id
timestamp
type
under_pressure

In [35]:
cols = ['id', 'player_id', 'location', 'match_id', 'timestamp', 'pass_body_part', 'pass_end_location', 'pass_height', 'pass_outcome', 'pass_shot_assist', 'pass_goal_assist', 'pass_through_ball', 'pass_type', 'under_pressure']
cols

['id',
 'player_id',
 'location',
 'match_id',
 'timestamp',
 'pass_body_part',
 'pass_end_location',
 'pass_height',
 'pass_outcome',
 'pass_shot_assist',
 'pass_goal_assist',
 'pass_through_ball',
 'pass_type',
 'under_pressure']

In [36]:
passes_df[cols].pass_body_part.unique()

array(['Head', nan, 'Right Foot', 'Keeper Arm', 'Left Foot', 'Drop Kick',
       'Other', 'No Touch'], dtype=object)

In [37]:
passes_df[cols].pass_outcome.unique()

array([nan, 'Incomplete', 'Out', 'Unknown', 'Pass Offside',
       'Injury Clearance'], dtype=object)

In [38]:
passes_df[cols].pass_through_ball.unique()

array([nan, True], dtype=object)

In [39]:
passes_df[cols].pass_type.unique()

array(['Recovery', nan, 'Throw-in', 'Free Kick', 'Goal Kick',
       'Interception', 'Kick Off', 'Corner'], dtype=object)

In [40]:
passes_df[cols].under_pressure.unique()

array([nan, True], dtype=object)

In [41]:
events.info()

NameError: name 'events' is not defined

In [ ]:
events.type.unique()

In [ ]:
shot_events = events[events['type'] == 'Shot']
shot_events['end_z'].max()

In [ ]:
shot_events['shot_end_location']

In [ ]:
related

In [ ]:
help(parser)